server:
  port: ${port:8015}

spring:
  redis:
    database: 0
    host: 192.168.186.88
    port: 6379
    password: 123456

# 在dev环境开启mybatis的日志打印
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 设置域名，在java代码中获取(设置cookie)，这里是资源配置
website:
  domain-name: imoocnews.com
