############################################################
#
# 文章页面静态化微服务
# web访问端口号  约定：8002
#
############################################################
server:
#  port: 8002
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可

############################################################
#
# 配置项目信息
#
############################################################
spring:
  profiles:
    active: dev   # yml中配置文件的环境配置，dev：开发环境，test：测试环境，prod：生产环境
  application:
    name: service-article
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      uri: mongodb://root:123456@192.168.186.88:27017
      database: imooc-news
  freemarker:
    charset: UTF-8
    content-type: text/html
    suffix: .ftl
    template-loader-path: classpath:/templates/
  rabbitmq:
    host: 192.168.186.88
    port: 5672
    username: admin
    password: admin
    virtual-host: imooc-news-dev




# 定义freemarker生成的html位置
freemarker:
  html:
    target: D:\Spring Cloud分布式微服务实战L259\freemarker_target
    article: D:\Spring Cloud分布式微服务实战L259\课程资料\apache-tomcat-8.5.31\webapps\imooc-news\portal\a
